//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPizza_PCL.Model
{
    using System;

    public partial class Narudzbe
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    
        public int NarudzbaId { get; set; }
        public int KorisnikId { get; set; }
        public int StatusNarudzbeId { get; set; }
        public System.DateTime DatumNarudzbe { get; set; }
        public Nullable<bool> OtkazanaNarudzba { get; set; }
        public string AdresaZaDostavu { get; set; }
        public string BrojTelefona { get; set; }
    }
}
