//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPizza_PCL.Model
{
    public class UlogeKorisnika
    {    
        public int UlogaKorisnikaId { get; set; }
        public string Uloga { get; set; }
        public string Opis { get; set; }
    }
}
