

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyPizza_API.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class MyPizzaEntities1 : DbContext
{
    public MyPizzaEntities1()
        : base("name=MyPizzaEntities1")
    {
        Configuration.ProxyCreationEnabled = false;
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<CijenePizza> CijenePizza { get; set; }

    public virtual DbSet<DodatniSastojci> DodatniSastojci { get; set; }

    public virtual DbSet<Gradovi> Gradovi { get; set; }

    public virtual DbSet<Korisnici> Korisnici { get; set; }

    public virtual DbSet<KorisnickeUloge> KorisnickeUloge { get; set; }

    public virtual DbSet<Narudzbe> Narudzbe { get; set; }

    public virtual DbSet<NarudzbePizze> NarudzbePizze { get; set; }

    public virtual DbSet<Ocjene> Ocjene { get; set; }

    public virtual DbSet<Pizze> Pizze { get; set; }

    public virtual DbSet<Racuni> Racuni { get; set; }

    public virtual DbSet<Sastojci> Sastojci { get; set; }

    public virtual DbSet<StatusiKorisnika> StatusiKorisnika { get; set; }

    public virtual DbSet<StatusiNarudzbi> StatusiNarudzbi { get; set; }

    public virtual DbSet<StatusiPizza> StatusiPizza { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<UlogeKorisnika> UlogeKorisnika { get; set; }

    public virtual DbSet<VelicinePizza> VelicinePizza { get; set; }

    public virtual DbSet<VrstePizza> VrstePizza { get; set; }

    public virtual DbSet<VrsteSastojci> VrsteSastojci { get; set; }


    public virtual ObjectResult<Nullable<decimal>> myPizza_Korisnici_Insert(string ime, string prezime, string korisnickoIme, string lozinkaHash, string lozinkaSalt, string email, string brojTelefona, Nullable<System.DateTime> datumRegistracije, Nullable<int> statusKorisnikaId, Nullable<int> gradId, string ulica)
    {

        var imeParameter = ime != null ?
            new ObjectParameter("ime", ime) :
            new ObjectParameter("ime", typeof(string));


        var prezimeParameter = prezime != null ?
            new ObjectParameter("prezime", prezime) :
            new ObjectParameter("prezime", typeof(string));


        var korisnickoImeParameter = korisnickoIme != null ?
            new ObjectParameter("korisnickoIme", korisnickoIme) :
            new ObjectParameter("korisnickoIme", typeof(string));


        var lozinkaHashParameter = lozinkaHash != null ?
            new ObjectParameter("lozinkaHash", lozinkaHash) :
            new ObjectParameter("lozinkaHash", typeof(string));


        var lozinkaSaltParameter = lozinkaSalt != null ?
            new ObjectParameter("lozinkaSalt", lozinkaSalt) :
            new ObjectParameter("lozinkaSalt", typeof(string));


        var emailParameter = email != null ?
            new ObjectParameter("email", email) :
            new ObjectParameter("email", typeof(string));


        var brojTelefonaParameter = brojTelefona != null ?
            new ObjectParameter("brojTelefona", brojTelefona) :
            new ObjectParameter("brojTelefona", typeof(string));


        var datumRegistracijeParameter = datumRegistracije.HasValue ?
            new ObjectParameter("datumRegistracije", datumRegistracije) :
            new ObjectParameter("datumRegistracije", typeof(System.DateTime));


        var statusKorisnikaIdParameter = statusKorisnikaId.HasValue ?
            new ObjectParameter("statusKorisnikaId", statusKorisnikaId) :
            new ObjectParameter("statusKorisnikaId", typeof(int));


        var gradIdParameter = gradId.HasValue ?
            new ObjectParameter("gradId", gradId) :
            new ObjectParameter("gradId", typeof(int));


        var ulicaParameter = ulica != null ?
            new ObjectParameter("ulica", ulica) :
            new ObjectParameter("ulica", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("myPizza_Korisnici_Insert", imeParameter, prezimeParameter, korisnickoImeParameter, lozinkaHashParameter, lozinkaSaltParameter, emailParameter, brojTelefonaParameter, datumRegistracijeParameter, statusKorisnikaIdParameter, gradIdParameter, ulicaParameter);
    }


    public virtual ObjectResult<myPizza_Korisnici_SelectByImePrezime_Result> myPizza_Korisnici_SelectByImePrezime(string imePrezime)
    {

        var imePrezimeParameter = imePrezime != null ?
            new ObjectParameter("imePrezime", imePrezime) :
            new ObjectParameter("imePrezime", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<myPizza_Korisnici_SelectByImePrezime_Result>("myPizza_Korisnici_SelectByImePrezime", imePrezimeParameter);
    }


    public virtual int myPizza_KorisnickeUloge_Insert(Nullable<int> korisnikId, Nullable<int> ulogaKorisnikaId, Nullable<System.DateTime> datumIzmjene)
    {

        var korisnikIdParameter = korisnikId.HasValue ?
            new ObjectParameter("korisnikId", korisnikId) :
            new ObjectParameter("korisnikId", typeof(int));


        var ulogaKorisnikaIdParameter = ulogaKorisnikaId.HasValue ?
            new ObjectParameter("ulogaKorisnikaId", ulogaKorisnikaId) :
            new ObjectParameter("ulogaKorisnikaId", typeof(int));


        var datumIzmjeneParameter = datumIzmjene.HasValue ?
            new ObjectParameter("datumIzmjene", datumIzmjene) :
            new ObjectParameter("datumIzmjene", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("myPizza_KorisnickeUloge_Insert", korisnikIdParameter, ulogaKorisnikaIdParameter, datumIzmjeneParameter);
    }


    public virtual ObjectResult<Nullable<decimal>> myPizza_VrstePizza_Insert(string vrsta, string opis, Nullable<System.DateTime> datumDodavanja, Nullable<System.DateTime> datumIzmjene, byte[] slika, byte[] slikaThumb)
    {

        var vrstaParameter = vrsta != null ?
            new ObjectParameter("vrsta", vrsta) :
            new ObjectParameter("vrsta", typeof(string));


        var opisParameter = opis != null ?
            new ObjectParameter("opis", opis) :
            new ObjectParameter("opis", typeof(string));


        var datumDodavanjaParameter = datumDodavanja.HasValue ?
            new ObjectParameter("datumDodavanja", datumDodavanja) :
            new ObjectParameter("datumDodavanja", typeof(System.DateTime));


        var datumIzmjeneParameter = datumIzmjene.HasValue ?
            new ObjectParameter("datumIzmjene", datumIzmjene) :
            new ObjectParameter("datumIzmjene", typeof(System.DateTime));


        var slikaParameter = slika != null ?
            new ObjectParameter("slika", slika) :
            new ObjectParameter("slika", typeof(byte[]));


        var slikaThumbParameter = slikaThumb != null ?
            new ObjectParameter("slikaThumb", slikaThumb) :
            new ObjectParameter("slikaThumb", typeof(byte[]));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("myPizza_VrstePizza_Insert", vrstaParameter, opisParameter, datumDodavanjaParameter, datumIzmjeneParameter, slikaParameter, slikaThumbParameter);
    }


    public virtual int myPizza_VrsteSastojci_Insert(Nullable<int> vrstaId, Nullable<int> sastojakId)
    {

        var vrstaIdParameter = vrstaId.HasValue ?
            new ObjectParameter("vrstaId", vrstaId) :
            new ObjectParameter("vrstaId", typeof(int));


        var sastojakIdParameter = sastojakId.HasValue ?
            new ObjectParameter("sastojakId", sastojakId) :
            new ObjectParameter("sastojakId", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("myPizza_VrsteSastojci_Insert", vrstaIdParameter, sastojakIdParameter);
    }


    public virtual ObjectResult<VrstePizza> myPizza_GetAktivnePizze()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VrstePizza>("myPizza_GetAktivnePizze");
    }


    public virtual ObjectResult<VrstePizza> myPizza_GetAktivnePizze(MergeOption mergeOption)
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VrstePizza>("myPizza_GetAktivnePizze", mergeOption);
    }


    public virtual ObjectResult<myPizza_GetVelPizza_Result> myPizza_GetVelPizza(Nullable<int> vrstaPizzeID)
    {

        var vrstaPizzeIDParameter = vrstaPizzeID.HasValue ?
            new ObjectParameter("vrstaPizzeID", vrstaPizzeID) :
            new ObjectParameter("vrstaPizzeID", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<myPizza_GetVelPizza_Result>("myPizza_GetVelPizza", vrstaPizzeIDParameter);
    }


    public virtual int myPizza_Ocjene_LikeDislike(Nullable<int> vrstaPizzaId, Nullable<int> korisnikId, Nullable<System.DateTime> datumOcjnene, Nullable<bool> svidja, Nullable<bool> neSvidja, Nullable<int> ocjena)
    {

        var vrstaPizzaIdParameter = vrstaPizzaId.HasValue ?
            new ObjectParameter("vrstaPizzaId", vrstaPizzaId) :
            new ObjectParameter("vrstaPizzaId", typeof(int));


        var korisnikIdParameter = korisnikId.HasValue ?
            new ObjectParameter("korisnikId", korisnikId) :
            new ObjectParameter("korisnikId", typeof(int));


        var datumOcjneneParameter = datumOcjnene.HasValue ?
            new ObjectParameter("datumOcjnene", datumOcjnene) :
            new ObjectParameter("datumOcjnene", typeof(System.DateTime));


        var svidjaParameter = svidja.HasValue ?
            new ObjectParameter("svidja", svidja) :
            new ObjectParameter("svidja", typeof(bool));


        var neSvidjaParameter = neSvidja.HasValue ?
            new ObjectParameter("neSvidja", neSvidja) :
            new ObjectParameter("neSvidja", typeof(bool));


        var ocjenaParameter = ocjena.HasValue ?
            new ObjectParameter("ocjena", ocjena) :
            new ObjectParameter("ocjena", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("myPizza_Ocjene_LikeDislike", vrstaPizzaIdParameter, korisnikIdParameter, datumOcjneneParameter, svidjaParameter, neSvidjaParameter, ocjenaParameter);
    }


    public virtual ObjectResult<myPizza_GetOcjeneForVrsta_Result> myPizza_GetOcjeneForVrsta(Nullable<int> vrstaPizzeId)
    {

        var vrstaPizzeIdParameter = vrstaPizzeId.HasValue ?
            new ObjectParameter("vrstaPizzeId", vrstaPizzeId) :
            new ObjectParameter("vrstaPizzeId", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<myPizza_GetOcjeneForVrsta_Result>("myPizza_GetOcjeneForVrsta", vrstaPizzeIdParameter);
    }


    public virtual ObjectResult<Sastojci> myPizza_GetSastojciForVrsta(Nullable<int> vrstaId)
    {

        var vrstaIdParameter = vrstaId.HasValue ?
            new ObjectParameter("vrstaId", vrstaId) :
            new ObjectParameter("vrstaId", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sastojci>("myPizza_GetSastojciForVrsta", vrstaIdParameter);
    }


    public virtual ObjectResult<Sastojci> myPizza_GetSastojciForVrsta(Nullable<int> vrstaId, MergeOption mergeOption)
    {

        var vrstaIdParameter = vrstaId.HasValue ?
            new ObjectParameter("vrstaId", vrstaId) :
            new ObjectParameter("vrstaId", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sastojci>("myPizza_GetSastojciForVrsta", mergeOption, vrstaIdParameter);
    }


    public virtual ObjectResult<Nullable<decimal>> MyPizza_Narudzbe_Insert(Nullable<int> korisnikId, Nullable<int> statusNarudzbeId, Nullable<System.DateTime> datumNarudzbe, Nullable<bool> otkazanaNarudzba, string adresaZaDosavu, string brojTelefona)
    {

        var korisnikIdParameter = korisnikId.HasValue ?
            new ObjectParameter("korisnikId", korisnikId) :
            new ObjectParameter("korisnikId", typeof(int));


        var statusNarudzbeIdParameter = statusNarudzbeId.HasValue ?
            new ObjectParameter("statusNarudzbeId", statusNarudzbeId) :
            new ObjectParameter("statusNarudzbeId", typeof(int));


        var datumNarudzbeParameter = datumNarudzbe.HasValue ?
            new ObjectParameter("datumNarudzbe", datumNarudzbe) :
            new ObjectParameter("datumNarudzbe", typeof(System.DateTime));


        var otkazanaNarudzbaParameter = otkazanaNarudzba.HasValue ?
            new ObjectParameter("otkazanaNarudzba", otkazanaNarudzba) :
            new ObjectParameter("otkazanaNarudzba", typeof(bool));


        var adresaZaDosavuParameter = adresaZaDosavu != null ?
            new ObjectParameter("adresaZaDosavu", adresaZaDosavu) :
            new ObjectParameter("adresaZaDosavu", typeof(string));


        var brojTelefonaParameter = brojTelefona != null ?
            new ObjectParameter("brojTelefona", brojTelefona) :
            new ObjectParameter("brojTelefona", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("MyPizza_Narudzbe_Insert", korisnikIdParameter, statusNarudzbeIdParameter, datumNarudzbeParameter, otkazanaNarudzbaParameter, adresaZaDosavuParameter, brojTelefonaParameter);
    }


    public virtual ObjectResult<Nullable<decimal>> myPizza_NarudzbePizze_Insert(Nullable<int> narudzbaId, Nullable<int> pizzaId, Nullable<int> kolicina, Nullable<decimal> cijena)
    {

        var narudzbaIdParameter = narudzbaId.HasValue ?
            new ObjectParameter("narudzbaId", narudzbaId) :
            new ObjectParameter("narudzbaId", typeof(int));


        var pizzaIdParameter = pizzaId.HasValue ?
            new ObjectParameter("pizzaId", pizzaId) :
            new ObjectParameter("pizzaId", typeof(int));


        var kolicinaParameter = kolicina.HasValue ?
            new ObjectParameter("kolicina", kolicina) :
            new ObjectParameter("kolicina", typeof(int));


        var cijenaParameter = cijena.HasValue ?
            new ObjectParameter("cijena", cijena) :
            new ObjectParameter("cijena", typeof(decimal));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("myPizza_NarudzbePizze_Insert", narudzbaIdParameter, pizzaIdParameter, kolicinaParameter, cijenaParameter);
    }


    public virtual int myPizza_DodatniSastojci_Insert(Nullable<int> narudzbaPizzaId, Nullable<int> sastojakId)
    {

        var narudzbaPizzaIdParameter = narudzbaPizzaId.HasValue ?
            new ObjectParameter("narudzbaPizzaId", narudzbaPizzaId) :
            new ObjectParameter("narudzbaPizzaId", typeof(int));


        var sastojakIdParameter = sastojakId.HasValue ?
            new ObjectParameter("sastojakId", sastojakId) :
            new ObjectParameter("sastojakId", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("myPizza_DodatniSastojci_Insert", narudzbaPizzaIdParameter, sastojakIdParameter);
    }


    public virtual int myPizza_Racun_Insert(Nullable<System.DateTime> datum, Nullable<int> narudzbaId, Nullable<int> korisnikId, Nullable<decimal> cijenaSaPdv, Nullable<decimal> cijenaBezPdv)
    {

        var datumParameter = datum.HasValue ?
            new ObjectParameter("datum", datum) :
            new ObjectParameter("datum", typeof(System.DateTime));


        var narudzbaIdParameter = narudzbaId.HasValue ?
            new ObjectParameter("narudzbaId", narudzbaId) :
            new ObjectParameter("narudzbaId", typeof(int));


        var korisnikIdParameter = korisnikId.HasValue ?
            new ObjectParameter("korisnikId", korisnikId) :
            new ObjectParameter("korisnikId", typeof(int));


        var cijenaSaPdvParameter = cijenaSaPdv.HasValue ?
            new ObjectParameter("cijenaSaPdv", cijenaSaPdv) :
            new ObjectParameter("cijenaSaPdv", typeof(decimal));


        var cijenaBezPdvParameter = cijenaBezPdv.HasValue ?
            new ObjectParameter("cijenaBezPdv", cijenaBezPdv) :
            new ObjectParameter("cijenaBezPdv", typeof(decimal));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("myPizza_Racun_Insert", datumParameter, narudzbaIdParameter, korisnikIdParameter, cijenaSaPdvParameter, cijenaBezPdvParameter);
    }


    public virtual ObjectResult<myPizza_Racun_GetForKorisnik_Result> myPizza_Racun_GetForKorisnik(Nullable<int> korisnikId)
    {

        var korisnikIdParameter = korisnikId.HasValue ?
            new ObjectParameter("korisnikId", korisnikId) :
            new ObjectParameter("korisnikId", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<myPizza_Racun_GetForKorisnik_Result>("myPizza_Racun_GetForKorisnik", korisnikIdParameter);
    }


    public virtual ObjectResult<myPizza_Narudzbe_SelectAktivne_Result> myPizza_Narudzbe_SelectAktivne()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<myPizza_Narudzbe_SelectAktivne_Result>("myPizza_Narudzbe_SelectAktivne");
    }


    public virtual ObjectResult<myPizza_Narudzbe_Details_Result> myPizza_Narudzbe_Details(Nullable<int> narudzbaId)
    {

        var narudzbaIdParameter = narudzbaId.HasValue ?
            new ObjectParameter("narudzbaId", narudzbaId) :
            new ObjectParameter("narudzbaId", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<myPizza_Narudzbe_Details_Result>("myPizza_Narudzbe_Details", narudzbaIdParameter);
    }


    public virtual int myPizza_NarudzbaUpdate(Nullable<int> narudzbaId)
    {

        var narudzbaIdParameter = narudzbaId.HasValue ?
            new ObjectParameter("narudzbaId", narudzbaId) :
            new ObjectParameter("narudzbaId", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("myPizza_NarudzbaUpdate", narudzbaIdParameter);
    }


    public virtual ObjectResult<myPizza_Narudzbe_SelectObradjene_Result> myPizza_Narudzbe_SelectObradjene()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<myPizza_Narudzbe_SelectObradjene_Result>("myPizza_Narudzbe_SelectObradjene");
    }


    public virtual ObjectResult<myPizza_Narudzbe_SelectOdbijene_Result> myPizza_Narudzbe_SelectOdbijene()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<myPizza_Narudzbe_SelectOdbijene_Result>("myPizza_Narudzbe_SelectOdbijene");
    }


    public virtual ObjectResult<VrstePizza> myPizza_VrstePizza_SelectById(Nullable<int> vrstaPizzeId)
    {

        var vrstaPizzeIdParameter = vrstaPizzeId.HasValue ?
            new ObjectParameter("vrstaPizzeId", vrstaPizzeId) :
            new ObjectParameter("vrstaPizzeId", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VrstePizza>("myPizza_VrstePizza_SelectById", vrstaPizzeIdParameter);
    }


    public virtual ObjectResult<VrstePizza> myPizza_VrstePizza_SelectById(Nullable<int> vrstaPizzeId, MergeOption mergeOption)
    {

        var vrstaPizzeIdParameter = vrstaPizzeId.HasValue ?
            new ObjectParameter("vrstaPizzeId", vrstaPizzeId) :
            new ObjectParameter("vrstaPizzeId", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VrstePizza>("myPizza_VrstePizza_SelectById", mergeOption, vrstaPizzeIdParameter);
    }


    public virtual ObjectResult<myPizza_Narudzbe_SelectByUserId_Result> myPizza_Narudzbe_SelectByUserId(Nullable<int> korisnikId)
    {

        var korisnikIdParameter = korisnikId.HasValue ?
            new ObjectParameter("KorisnikId", korisnikId) :
            new ObjectParameter("KorisnikId", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<myPizza_Narudzbe_SelectByUserId_Result>("myPizza_Narudzbe_SelectByUserId", korisnikIdParameter);
    }


    public virtual ObjectResult<Racuni> myPizza_Racun_GetByUserId(Nullable<int> korisnikId)
    {

        var korisnikIdParameter = korisnikId.HasValue ?
            new ObjectParameter("korisnikId", korisnikId) :
            new ObjectParameter("korisnikId", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Racuni>("myPizza_Racun_GetByUserId", korisnikIdParameter);
    }


    public virtual ObjectResult<Racuni> myPizza_Racun_GetByUserId(Nullable<int> korisnikId, MergeOption mergeOption)
    {

        var korisnikIdParameter = korisnikId.HasValue ?
            new ObjectParameter("korisnikId", korisnikId) :
            new ObjectParameter("korisnikId", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Racuni>("myPizza_Racun_GetByUserId", mergeOption, korisnikIdParameter);
    }


    public virtual ObjectResult<myPizza_Vrste_SelectTop_Result> myPizza_Vrste_SelectTop()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<myPizza_Vrste_SelectTop_Result>("myPizza_Vrste_SelectTop");
    }


    public virtual ObjectResult<myPizza_DodatniSastojciTop_Result> myPizza_DodatniSastojciTop()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<myPizza_DodatniSastojciTop_Result>("myPizza_DodatniSastojciTop");
    }


    public virtual ObjectResult<myPizza_Korisnici_SelectTop_Result> myPizza_Korisnici_SelectTop()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<myPizza_Korisnici_SelectTop_Result>("myPizza_Korisnici_SelectTop");
    }


    public virtual ObjectResult<myPizza_Narudzbe_SelectAll_Result> myPizza_Narudzbe_SelectAll()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<myPizza_Narudzbe_SelectAll_Result>("myPizza_Narudzbe_SelectAll");
    }


    public virtual ObjectResult<myPizza_Korisnici_ImePrezimeId_Result> myPizza_Korisnici_ImePrezimeId()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<myPizza_Korisnici_ImePrezimeId_Result>("myPizza_Korisnici_ImePrezimeId");
    }


    public virtual ObjectResult<myPizza_Narudzbe_ByDate_Result> myPizza_Narudzbe_ByDate(Nullable<System.DateTime> datumOdNarudzbe, Nullable<System.DateTime> datumDoNarudzbe)
    {

        var datumOdNarudzbeParameter = datumOdNarudzbe.HasValue ?
            new ObjectParameter("datumOdNarudzbe", datumOdNarudzbe) :
            new ObjectParameter("datumOdNarudzbe", typeof(System.DateTime));


        var datumDoNarudzbeParameter = datumDoNarudzbe.HasValue ?
            new ObjectParameter("datumDoNarudzbe", datumDoNarudzbe) :
            new ObjectParameter("datumDoNarudzbe", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<myPizza_Narudzbe_ByDate_Result>("myPizza_Narudzbe_ByDate", datumOdNarudzbeParameter, datumDoNarudzbeParameter);
    }

}

}

