
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyPizza_API.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Narudzbe
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Narudzbe()
    {

        this.NarudzbePizze = new HashSet<NarudzbePizze>();

        this.Racuni = new HashSet<Racuni>();

    }


    public int NarudzbaId { get; set; }

    public int KorisnikId { get; set; }

    public int StatusNarudzbeId { get; set; }

    public System.DateTime DatumNarudzbe { get; set; }

    public Nullable<bool> OtkazanaNarudzba { get; set; }

    public string AdresaZaDostavu { get; set; }



    public virtual Korisnici Korisnici { get; set; }

    public virtual StatusiNarudzbi StatusiNarudzbi { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<NarudzbePizze> NarudzbePizze { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Racuni> Racuni { get; set; }

}

}
