//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPizza_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocjene
    {
        public int OcjenaId { get; set; }
        public int PizzaId { get; set; }
        public int KorisnikId { get; set; }
        public System.DateTime DatumOcjene { get; set; }
        public double Ocjena { get; set; }
        public string Komentar { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
        public virtual Pizze Pizze { get; set; }
    }
}
