//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPizza_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pizze
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pizze()
        {
            this.NarudzbePizze = new HashSet<NarudzbePizze>();
            this.Ocjene = new HashSet<Ocjene>();
        }
    
        public int PizzaId { get; set; }
        public int VrstaId { get; set; }
        public int VelicinaId { get; set; }
        public int StatusPizzeId { get; set; }
        public int CijenaId { get; set; }
        public Nullable<double> Cijena { get; set; }
    
        public virtual CijenePizza CijenePizza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NarudzbePizze> NarudzbePizze { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ocjene> Ocjene { get; set; }
        public virtual StatusiPizza StatusiPizza { get; set; }
        public virtual VelicinePizza VelicinePizza { get; set; }
        public virtual VrstePizza VrstePizza { get; set; }
    }
}
