
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyPizza_API.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Racuni
{

    public int RacunId { get; set; }

    public System.DateTime Datum { get; set; }

    public int NarudzbaId { get; set; }

    public int KorisnikId { get; set; }

    public decimal CijenaSaPDV { get; set; }

    public decimal CijenaBezPDV { get; set; }



    public virtual Korisnici Korisnici { get; set; }

    public virtual Narudzbe Narudzbe { get; set; }

}

}
