
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyPizza_API.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Sastojci
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Sastojci()
    {

        this.DodatniSastojci = new HashSet<DodatniSastojci>();

        this.VrsteSastojci = new HashSet<VrsteSastojci>();

    }


    public int SastojakId { get; set; }

    public string Sastojak { get; set; }

    public double BaznaCijena { get; set; }

    public double DodatnaCijena { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DodatniSastojci> DodatniSastojci { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VrsteSastojci> VrsteSastojci { get; set; }

}

}
