//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPizza_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusiPizza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StatusiPizza()
        {
            this.Pizze = new HashSet<Pizze>();
        }
    
        public int StatusPizzeId { get; set; }
        public string StatusPizze { get; set; }
        public string Opis { get; set; }
        public Nullable<System.DateTime> DatumIzmjene { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pizze> Pizze { get; set; }
    }
}
