
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MyPizza_API.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UlogeKorisnika
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UlogeKorisnika()
    {

        this.KorisnickeUloge = new HashSet<KorisnickeUloge>();

    }


    public int UlogaKorisnikaId { get; set; }

    public string Uloga { get; set; }

    public string Opis { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<KorisnickeUloge> KorisnickeUloge { get; set; }

}

}
